# Generated by rextendr::document(); do NOT edit by hand.
#
# This placeholder is checked in so the R sources are coherent before the Rust
# library is built. Running `rextendr::document()` (after `src/rust/src/lib.rs`
# compiles against a pinned topica) regenerates this file and the native
# registration. Until then, `stm()` cannot fit — the `.Call` below has no
# registered symbol.

#' @useDynLib faSTM, .registration = TRUE
#' @keywords internal
#' @noRd
fit_stm <- function(docs_flat, doc_lens, num_types, num_topics, em_iters,
                    em_tol, sigma_shrink, prevalence, num_features,
                    content_groups, num_groups, init_spectral, gamma_l1_alpha,
                    diagonal, seed, inference, batch_size, tau, kappa) {
  .Call(
    "wrap__fit_stm",
    docs_flat, doc_lens, num_types, num_topics, em_iters, em_tol, sigma_shrink,
    prevalence, num_features, content_groups, num_groups, init_spectral,
    gamma_l1_alpha, diagonal, seed, inference, batch_size, tau, kappa,
    PACKAGE = "faSTM"
  )
}
