# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib faSTM, .registration = TRUE
NULL

# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_faSTM_wrappers", use_symbols = TRUE, package_name = "faSTM")

#' @usage NULL
#' @useDynLib faSTM, .registration = TRUE
NULL

#' Fit a structural topic model and return its raw arrays.
#'
#' Inputs are pre-converted in `R/stm.R`:
#' - `docs_flat` / `doc_lens`: documents as one concatenated 0-based token-id
#'   stream plus per-document lengths (counts already expanded). Reassembled
#'   here into `Vec<Vec<u32>>`, the shape `fit_ctm` wants.
#' - `prevalence`: row-major D×P design matrix flattened (NULL if none).
#' - `content_groups`: per-doc 0-based group id (NULL if none); `num_groups`.
#'
#' `inference`: "batch" -> `fit_ctm` (parity-validated). "svi" -> `fit_ctm_svi`
#' once topica #231 PR B (STM-SVI) is in the pinned revision; the R layer gates
#' the prevalence/content + svi combination until then.
fit_stm <- function(docs_flat, doc_lens, num_types, num_topics, em_iters, em_tol, sigma_shrink, prevalence, num_features, content_groups, num_groups, init_spectral, init_beta, gamma_l1_alpha, diagonal, seed, inference, batch_size, tau, kappa, num_threads) .Call(wrap__fit_stm, docs_flat, doc_lens, num_types, num_topics, em_iters, em_tol, sigma_shrink, prevalence, num_features, content_groups, num_groups, init_spectral, init_beta, gamma_l1_alpha, diagonal, seed, inference, batch_size, tau, kappa, num_threads)

#' Out-of-sample topic inference: for each new document, run the variational
#' E-step against fixed globals (β, μ, Σ⁻¹) and return θ. Documents are passed
#' sparse — `words` are 0-based ids into the *fitted model's* vocabulary
#' (out-of-vocabulary terms dropped by the R caller) with their `counts`,
#' concatenated, plus per-document term counts `doc_nterms`.
infer_theta_new <- function(beta_flat, num_topics, num_types, mu, siginv, words, counts, doc_nterms) .Call(wrap__infer_theta_new, beta_flat, num_topics, num_types, mu, siginv, words, counts, doc_nterms)

#' LDA topic-word matrix via topica's CVB0 (deterministic collapsed variational
#' Bayes), to seed a "replicate stm's LDA init" STM fit. Mirrors stm's
#' collapsed-Gibbs LDA initialization; the result is fed back as `init_beta`.
#' Returns K*V row-major topic-word probabilities.
lda_init_beta <- function(docs_flat, doc_lens, num_types, num_topics, iters, alpha, beta, seed) .Call(wrap__lda_init_beta, docs_flat, doc_lens, num_types, num_topics, iters, alpha, beta, seed)

# nolint end
